syntax = "proto3";
package mnstrv2;

import "google/protobuf/timestamp.proto";
import "mnstr.proto";
import "users.proto";

message Battle {
  string id = 1;
  User challenger = 2;
  Mnstr challenger_mnstr = 3;
  User opponent = 4;
  Mnstr opponent_mnstr = 5;
  User winner = 6;
  Mnstr winner_mnstr = 7;
  repeated BattleLog logs = 8;
  repeated BattleStatus statuses = 9;
}

message BattleLog {
  string id = 1;
  string battle_id = 2;
  User user = 3;
  Mnstr mnstr = 4;
  BattleAction action = 5;
  string data = 6;
  google.protobuf.Timestamp created_at = 7;
}

message BattleStatus {
  string id = 1;
  User user = 2;
  Mnstr mnstr = 3;
  User opponent = 4;
  Battle battle = 5;
  BattleStatusState status = 6;
  google.protobuf.Timestamp updated_at = 8;
}

enum BattleStatusState {
  BATTLE_STATUS_STATE_UNSPECIFIED = 0;
  BATTLE_STATUS_STATE_IN_QUEUE = 1;
  BATTLE_STATUS_STATE_IN_BATTLE = 2;
  BATTLE_STATUS_STATE_WATCHING = 3;
}

enum BattleAction {
  BATTLE_ACTION_UNSPECIFIED = 0;
  BATTLE_ACTION_JOINED = 1;
  BATTLE_ACTION_LEFT = 2;
  BATTLE_ACTION_READY = 3;
  BATTLE_ACTION_UNREADY = 4;
  BATTLE_ACTION_ACCEPTED = 6;
  BATTLE_ACTION_REJECTED = 7;
  BATTLE_ACTION_CANCELLED = 8;
  BATTLE_ACTION_WATCHING = 9;
  BATTLE_ACTION_LIST = 10;
  BATTLE_ACTION_CHALLENGE = 11;
  BATTLE_ACTION_ACCEPT = 12;
  BATTLE_ACTION_REJECT = 13;
  BATTLE_ACTION_GAME_STARTED = 14;
  BATTLE_ACTION_GAME_ENDED = 15;
  BATTLE_ACTION_MNSTR_CHOSEN = 16;
  BATTLE_ACTION_REJOIN = 18;
  BATTLE_ACTION_REJOINED = 19;
  BATTLE_ACTION_ATTACK = 20;
  BATTLE_ACTION_DEFEND = 21;
  BATTLE_ACTION_MAGIC = 22;
  BATTLE_ACTION_ESCAPE = 23;
  BATTLE_ACTION_SORT_MNSTRS = 24;
}

message BattleJoinRequest {
  string user_id = 1;
}

message BattleActionRequest {
  string user_id = 1;
  BattleAction action = 2;
  optional string battle_id = 3;
}

message BattleActionResponse {
  bool success = 1;
  optional string error = 2;
  optional string message = 3;
  optional Battle battle = 4;
}

service BattleQueueService {
  rpc BattleJoin(BattleJoinRequest) returns (stream Battle);
  rpc BattleAction(BattleActionRequest) returns (BattleActionResponse);
}
